### ISSUE TITLE
Parse main Actor file and corresponding test files

### ISSUE THREAD

**Issue by jxs** [polyphene/kythera#16]
## Description
to be passed to the `Tester` of the `testing-framework`. Directory structure should be the following:

```
├── token.wasm
└── token.t
    ├── test1.wasm
    └── test2.wasm
 ```
Where `token.wasm` is the main Actor file, and `.wasm` files under a `.t` directory are considered tests.
Alternatively we should also support `token.t.wasm` file on the same dir as the `token.wasm` main Actor file.
In sum:

**- All .wasm files that are at the root of the kythera wasm folder are actors**
**- All .t.wasm files that are at the root of the kythera wasm folder are test actors**
**- All .wasm files that are in .t folders are test actors**

## Are you planning to do it yourself in a pull request?

Yes

**Comment by tchataigner** [comment]
Closed in https://github.com/polyphene/kythera/commit/45c9243c65948d4dd4f302ed69eefbb7f3fd7d4a
