### ISSUE TITLE
Local execution environment: base implementation

### ISSUE THREAD

**Issue by tchataigner** [polyphene/kythera#21]
The first thing we need to create to ensure a working Kythera toolset is a basic local execution environment that we can use to emulate the behavior of the Filecoin network at actor's runtime.

To do so we can get inspiration from @anorth [FVM Workbench](https://github.com/anorth/fvm-workbench) and the previously developed [Integration test framework](https://github.com/filecoin-project/ref-fvm/tree/master/testing/integration).

This base implementation should let us set some custom wasm binaries in a Blockstore, initialize different actor and execute their methods while getting messages' results and printing them.

Both a CLI command for test and an API of a lib should be made available.

_Thomas' note_ 

We should get the wasm binaries from a dedicated folder on the file system that follows a defined structure that can be discussed at implementation time.

**Comment by raulk** [comment]
Hey @tchataigner -- have you looked at Ganache in Ethereum?

**Comment by tchataigner** [comment]
Hey @raulk! Thanks for the heads up, really appreciate it :pray: 

The team had the opportunity to explore it and the capabilities that it brings to developers, and we got inspired by some of its functionalities to design Kythera! I would point out that in our current roadmap, until the end of Milestone 3, we do not have any RPC or HTTP or WS layer planed. Until then, we are focused on having an execution machine which works upon native actors and their tests, along some enhanced capabilities for developers in that environment (manipulate information at the machine level like `caller` or `origin`, gas reports, etc).

However, it is true that it would be nice to add that layer at a later date to allow for some external communication also.

Did you have anything in particular to point out while mentioning it?

**Comment by tchataigner** [comment]
Waiting for discussion to unfold but I consider this issue mostly tackled with https://github.com/polyphene/kythera/pull/12

**Comment by tchataigner** [comment]
Closing as I think we've reached a good foundation with https://github.com/polyphene/kythera/pull/55
